// Program where the user has to guess a number generated by a program.

import java.util.*;

public class GuessTheNumber {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int count = 0;
        int random = (int) (Math.random() * 100);
        System.out.println(random);
        System.out.println("You have to guess a number between 0 - 100. \nAre you ready!!!");
        int num;
        do{
            System.out.print("Enter your guess: ");
            num = sc.nextInt();
            count++;

            if (num < random) 
                System.out.println("The number is greater than your number!");
            
            else if(num > random)
                System.out.println("The number is lesser than your number!");

            else
                System.out.println("\nCongratulations!!! You guessed the right number :)");

        } while (num != random);
        
        System.out.println("Your number of guesses: " + count);
    }
}
